name: Python-Versions
on: [push, pull_request, release]

jobs:
  test:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.6", "3.7"]

    steps:
    - uses: actions/checkout@v1
    - name: Piping Secrets
      run: |
        echo ${{ secrets.firebase_creds }} >> ghsTools/tests/firestore_creds.json
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        cd ghsTools/tests
        pytest --emoji
